### ISSUE TITLE
Classic Era Update 1.15.0 (Season of Discovery)

### ISSUE THREAD

**Issue by maximus210793** [ketho-wow/VendorPrice#10]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.0 (Season of Discovery)?
Would be awesome, thanks a lot in advance!

**Comment by Ketho** [comment]
When I get back tomorrow I'll update it for SoD :)

**Comment by Ketho** [comment]
Should be updated now with https://github.com/ketho-wow/VendorPrice/commit/47ef4fa44dc51ea86bc80bf7276d24aac57588cc
