### ISSUE TITLE
[SoD] Phoenix Binding price error

### ISSUE THREAD

**Issue by Raskelot** [ketho-wow/VendorPrice#11]
The current tooltip is 40s each, but the real price and the correct one is 24s and 81c as per wowhead.

https://www.wowhead.com/classic/item=210781/phoenix-bindings

**Comment by Ketho** [comment]
Well dang, I have no idea how wowhead gets the correct price. It's 40 silver according to [GetItemInfo](https://warcraft.wiki.gg/wiki/API_GetItemInfo) on the 1.15.0 PTR and the [ItemSparse](https://wago.tools/db2/ItemSparse?build=1.15.0.52610&filter[ID]=210781) DBC. I'm really not sure where the actual price of 24s and 81c would be...

![image](https://github.com/ketho-wow/VendorPrice/assets/1073877/b2564eed-0efc-4bd8-9abb-740458e27771)

![image](https://github.com/ketho-wow/VendorPrice/assets/1073877/18a02d06-4ad7-4b6d-9b45-0968005d812d)

**Comment by Raskelot** [comment]
Could have been a recent fix, because 40s it triple the mats cost so we could just craft and vendor it. I tried and vendor couple before realizing the addon was in error and I lost couple of silver to 1 gold, no big deal, but would be nice to have the correct value in game.
