### ISSUE TITLE
Random price showing for equipped quiver

### ISSUE THREAD

**Issue by BusManTay** [ketho-wow/VendorPrice#12]
When I mouse over my quiver that is equipped, like this:
![image](https://github.com/ketho-wow/VendorPrice/assets/69523238/81ea7fd4-249e-4147-bc10-d56676b42a60)
It shows the value at 23g30s.
Of course that's not the vendor price, and it shows correctly when I have it in my bag:
![image](https://github.com/ketho-wow/VendorPrice/assets/69523238/aa5ee836-fb60-4fdf-9475-86a413be88e3)

**Comment by BusManTay** [comment]
I noticed today that the price seems to change based on how many arrows are in the quiver.

**Comment by Ketho** [comment]
Thanks for the extra info, Blizzard apparently had changed some bag constants in 1.15.0 which came as a surprise
