### ISSUE TITLE
Flash Cheapest Gray Functionality

### ISSUE THREAD

**Issue by ulsting** [ketho-wow/VendorPrice#3]
Why was this functionality removed?

What is the latest version of the add-on that still has that functionality, and is it strongly inadvisable to use that version for that feature?

**Comment by Ketho** [comment]
It was removed because I think it's bloat and other addons can do this better
The latest version that still has this feature should be [v1.1.5](https://github.com/ketho-wow/VendorPrice/blob/1.1.5/VendorPrice.lua#L24)

I would advise you to use [Scrap (Junk Seller)](https://www.curseforge.com/wow/addons/scrap) instead

**Comment by ulsting** [comment]
Thanks!

**Comment by ulsting** [comment]
I actually just tested [Scrap (Junk Seller)](https://www.curseforge.com/wow/addons/scrap) and while it does more easily identify scrap while also listing its sell price per unit, unforunately it does not also show sell price per stack =(, it does not have a native feature to highlight the least valuable scrap item/stack in inventory. I also don't event see a keybind for it in the settings.

Is there an addon for the addon that adds this functionality?

**Comment by Ketho** [comment]
Can you try this standalone addon which has the previously removed code for flashing cheapest greys
https://github.com/ketho-wow/FlashCheapestGrey/releases/tag/1.0

**Comment by ulsting** [comment]
Yeah that works great!

I think that feature is definitely worth having in the main addon. There are a lot of addons that show vendor price, but so far this is the only one I have found with his feature, which I think is genius and personally use quite frequently.

**Comment by Ketho** [comment]
I personally think this feature should be in a separate addon. VendorPrice should just do one simple thing, show the price on mouseover

But I might upload FlashCheapestGrey to Curse after some refactoring
