### ISSUE TITLE
Multiple quantities for "you will also receive" quests

### ISSUE THREAD

**Issue by jfaulk** [ketho-wow/VendorPrice#4]
![WoWScrnShot_101219_162614](https://user-images.githubusercontent.com/4193693/66707372-66689b00-ed0d-11e9-8a8a-0b6d5d0485fb.jpg)

**Comment by Ketho** [comment]
Thanks, I have an idea what's wrong but will have to find a low level quest to reproduce it
https://github.com/Gethe/wow-ui-source/blob/classic/FrameXML/QuestFrame.lua#L544-L546
