### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by gabbsmo** [ketho-wow/VendorPrice#6]
Disabled all other addons but vendor prices are not shown when hovering items in my bags. "Better Vendor Prices" work but I like the more minimal UI of this addon. I disabled all other addons. Also checked with guild mates that had the same issue.

**Comment by Ketho** [comment]
Are you playing on classic_era instead of wrath classic? I might have forgotten about classic_era when blizzard partially added vendor prices to wrath 😅

**Comment by gabbsmo** [comment]
It's Classic Era. Sorry for leaving that important part out.

**Comment by Ketho** [comment]
Thanks, it will be fixed in the next update, hopefully tomorrow

**Comment by Ketho** [comment]
It took a bit longer I suppose, should be working again in Classic Era 😅

**Comment by gabbsmo** [comment]
Works great now after the update. Thanks for the addon!
