### ISSUE TITLE
VendorPrice Not Working in Classic Era PTR

### ISSUE THREAD

**Issue by DustinChecketts** [ketho-wow/VendorPrice#9]
Hi Ketho! Love the simplicity and minimalist nature of your VendorPrice addon. I'm currently playing on Classic Era PTR (Hardcore), version 1.14.4 (50547), and can't manage to get the addon to work even when it is the only addon enabled. It populates the following error:

```
Message: Interface/AddOns/VendorPrice/VendorPrice.lua:15: attempt to call global 'ContainerIDToInventoryID' (a nil value)
Time: Sat Jul 22 23:39:07 2023
Count: 1
Stack: Interface/AddOns/VendorPrice/VendorPrice.lua:15: attempt to call global 'ContainerIDToInventoryID' (a nil value)
[string "@Interface/AddOns/VendorPrice/VendorPrice.lua"]:15: in main chunk

Locals: VP = <table> {
}
isVanilla = true
isWrath = false
SELL_PRICE_TEXT = "Sell Price:"
overridePrice = nil
CharacterBags = <table> {
 21 = true
 22 = true
 20 = true
 23 = true
}
(*temporary) = nil
(*temporary) = 5
(*temporary) = "attempt to call global 'ContainerIDToInventoryID' (a nil value)"
```

After some reading, it appears Blizzard continues to consolidate their API for Interface addons. I couldn't figure out the syntax, but I wonder if it is no longer necessary to reference isWrath or isVanilla anymore. I've also read that the new Classic Era WoW is built on the Dragonflight client. I don't know if this is helpful or not.

If I can provide any other information to help get this updated for the PTR and future Classic Era Hardcore release, just let me know.

**Comment by Ketho** [comment]
Thanks it should work now on the classic era ptr

**Comment by DustinChecketts** [comment]
Many thanks for the quick update. Confirming that everything is working on the Classic Era PTR.
